### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ManuelGil** [ManuelGil/Hacktoberfest#4]
Add favicon in [index.htm](https://github.com/ManuelGil/Hacktoberfest/blob/master/docs/index.htm)

**Comment by Enforeach** [comment]
Is it Done? if no I'll go

**Comment by ManuelGil** [comment]
@Enforeach  you can do it!

**Comment by cmwalshWVU** [comment]
Can i have access to push my branch to make a PR

**Comment by ManuelGil** [comment]
Done! Thanks @cmwalshWVU
